"""
SYSTEM_PARAMETERS

"""
EPSILON = 1E-12
#DEFAULT_STREAM_SIZE = 2**24
DEFAULT_STREAM_SIZE = 2**12
DEFAULT_BUFFER_SIZE_FOR_STREAM = DEFAULT_STREAM_SIZE / 4
DEFAULT_NUM_IN_MEMORY = 2**4
DEFAULT_MIN_HISTORY = 2**2


